name: Deploy to Azure App Service (Container)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Xhihangule-Property-Management
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preflight – required secrets
        shell: bash
        run: |
          required=(AZURE_CLIENT_ID AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID AZURE_RESOURCE_GROUP REGISTRY_LOGIN_SERVER REGISTRY_USERNAME REGISTRY_PASSWORD)
          for n in "${required[@]}"; do
            if [ -z "${!n}" ]; then
              echo "::error::Missing $n" && exit 1
            fi
          done

      - name: Azure login (OIDC)
        if: ${{ env.AZURE_CLIENT_ID != '' && env.AZURE_TENANT_ID != '' && env.AZURE_SUBSCRIPTION_ID != '' }}
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: Show workspace layout
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "-- client --" && ls -la client || true
          echo "-- server --" && ls -la server || true

      - name: Verify lockfile (client)
        continue-on-error: true
        run: |
          echo "PWD=$(pwd)" && ls -la
          if [ -f package-lock.json ]; then echo "Found client/package-lock.json"; else echo "::warning::client/package-lock.json missing"; fi
        working-directory: ./client
      - name: Install dependencies (client)
        run: |
          npm ci || npm install --no-audit --no-fund
        working-directory: ./client
      - name: Verify lockfile (server)
        continue-on-error: true
        run: |
          echo "PWD=$(pwd)" && ls -la
          if [ -f package-lock.json ]; then echo "Found server/package-lock.json"; else echo "::warning::server/package-lock.json missing"; fi
        working-directory: ./server
      - name: Install dependencies (server)
        run: |
          npm ci || npm install --no-audit --no-fund
        working-directory: ./server

      - name: Build application
        run: |
          cd client && npm run build
          cd ../server && npm run build
        env:
          CI: false

      - name: Build Docker image
        run: |
          docker build -t ${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} .
          docker tag ${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} ${{ env.AZURE_WEBAPP_NAME }}:latest

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
          docker tag ${{ env.AZURE_WEBAPP_NAME }}:latest ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:latest
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:latest

      - name: Verify image exists in ACR
        shell: bash
        run: |
          ACR_NAME=$(echo "${REGISTRY_LOGIN_SERVER}" | cut -d'.' -f1)
          echo "Checking repository '${AZURE_WEBAPP_NAME}' in ACR '${ACR_NAME}'"
          az acr repository show-tags -n "$ACR_NAME" --repository "$AZURE_WEBAPP_NAME" -o table || true

      - name: Ensure App Service container port setting
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --settings WEBSITES_PORT=8080

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}