name: Node Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
            package-lock.json
      - name: Show npm version and config
        run: |
          node -v
          npm -v
          npm config list
      - name: Install deps (root)
        run: |
          npm ci || npm install --no-audit --no-fund
      - name: Show workspace layout
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "-- client --" && ls -la client || true
          echo "-- server --" && ls -la server || true
      - name: Verify lockfile (client)
        continue-on-error: true
        run: |
          echo "PWD=$(pwd)" && ls -la
          if [ -f package-lock.json ]; then echo "Found client/package-lock.json"; else echo "::warning::client/package-lock.json missing"; fi
        working-directory: ./client
      - name: Install deps (client)
        run: |
          npm ci || npm install --no-audit --no-fund
        working-directory: ./client
      - name: Verify lockfile (server)
        continue-on-error: true
        run: |
          echo "PWD=$(pwd)" && ls -la
          if [ -f package-lock.json ]; then echo "Found server/package-lock.json"; else echo "::warning::server/package-lock.json missing"; fi
        working-directory: ./server
      - name: Install deps (server)
        run: |
          npm ci || npm install --no-audit --no-fund
        working-directory: ./server
      - run: npm run build


