name: Node Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      - name: Install deps (client)
        run: npm ci
        working-directory: ./client
      - name: Install deps (server)
        run: npm ci
        working-directory: ./server
      - run: npm run build


